theme: jekyll-theme-minimal
title: Fox Baudelaire
description: "Preferred pronouns: he, him, his. One of the above is an artist's rendition. The other is a cartoon."
logo: portrait_dual.png
show_downloads: false
