theme: jekyll-theme-minimal
title: Fox Baudelaire
description: >
  M.S. Student, University of Michigan
  B.S. Brandeis University ('20)
  A.S. Bunker Hill Comm. College ('17)
logo: portrait_dual.png
show_downloads: false
